/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutEngineeringRouteImport } from './routes/about/engineering'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications/$applicationId'
import { Route as CareersIndexRouteImport } from './routes/careers/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ContactEngineeringEnquiryRouteImport } from './routes/contact/engineering-enquiry'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesFaqsRouteImport } from './routes/resources/faqs'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsSolutionIdRouteImport } from './routes/solutions/$solutionId'
import { Route as TechnologyIndexRouteImport } from './routes/technology/index'
import { Route as TechnologyTechIdRouteImport } from './routes/technology/$techId'
import { Route as ProductsCategoryIndexRouteImport } from './routes/products/$category/index'
import { Route as ProductsCategoryIdRouteImport } from './routes/products/$category/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutEngineeringRoute = AboutEngineeringRouteImport.update({
  id: '/about/engineering',
  path: '/about/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactEngineeringEnquiryRoute =
  ContactEngineeringEnquiryRouteImport.update({
    id: '/contact/engineering-enquiry',
    path: '/contact/engineering-enquiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesFaqsRoute = ResourcesFaqsRouteImport.update({
  id: '/resources/faqs',
  path: '/resources/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSolutionIdRoute = SolutionsSolutionIdRouteImport.update({
  id: '/solutions/$solutionId',
  path: '/solutions/$solutionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyIndexRoute = TechnologyIndexRouteImport.update({
  id: '/technology/',
  path: '/technology/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyTechIdRoute = TechnologyTechIdRouteImport.update({
  id: '/technology/$techId',
  path: '/technology/$techId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIndexRoute = ProductsCategoryIndexRouteImport.update({
  id: '/products/$category/',
  path: '/products/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIdRoute = ProductsCategoryIdRouteImport.update({
  id: '/products/$category/$id',
  path: '/products/$category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/about/engineering': typeof AboutEngineeringRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/contact/engineering-enquiry': typeof ContactEngineeringEnquiryRoute
  '/resources/faqs': typeof ResourcesFaqsRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/technology/$techId': typeof TechnologyTechIdRoute
  '/about/': typeof AboutIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/technology/': typeof TechnologyIndexRoute
  '/products/$category/$id': typeof ProductsCategoryIdRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/about/engineering': typeof AboutEngineeringRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/contact/engineering-enquiry': typeof ContactEngineeringEnquiryRoute
  '/resources/faqs': typeof ResourcesFaqsRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/technology/$techId': typeof TechnologyTechIdRoute
  '/about': typeof AboutIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/careers': typeof CareersIndexRoute
  '/contact': typeof ContactIndexRoute
  '/products': typeof ProductsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/technology': typeof TechnologyIndexRoute
  '/products/$category/$id': typeof ProductsCategoryIdRoute
  '/products/$category': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/about/engineering': typeof AboutEngineeringRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/contact/engineering-enquiry': typeof ContactEngineeringEnquiryRoute
  '/resources/faqs': typeof ResourcesFaqsRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/technology/$techId': typeof TechnologyTechIdRoute
  '/about/': typeof AboutIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/technology/': typeof TechnologyIndexRoute
  '/products/$category/$id': typeof ProductsCategoryIdRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/about/engineering'
    | '/applications/$applicationId'
    | '/contact/engineering-enquiry'
    | '/resources/faqs'
    | '/solutions/$solutionId'
    | '/technology/$techId'
    | '/about/'
    | '/applications/'
    | '/careers/'
    | '/contact/'
    | '/products/'
    | '/resources/'
    | '/solutions/'
    | '/technology/'
    | '/products/$category/$id'
    | '/products/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/about/engineering'
    | '/applications/$applicationId'
    | '/contact/engineering-enquiry'
    | '/resources/faqs'
    | '/solutions/$solutionId'
    | '/technology/$techId'
    | '/about'
    | '/applications'
    | '/careers'
    | '/contact'
    | '/products'
    | '/resources'
    | '/solutions'
    | '/technology'
    | '/products/$category/$id'
    | '/products/$category'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/about/engineering'
    | '/applications/$applicationId'
    | '/contact/engineering-enquiry'
    | '/resources/faqs'
    | '/solutions/$solutionId'
    | '/technology/$techId'
    | '/about/'
    | '/applications/'
    | '/careers/'
    | '/contact/'
    | '/products/'
    | '/resources/'
    | '/solutions/'
    | '/technology/'
    | '/products/$category/$id'
    | '/products/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  AboutEngineeringRoute: typeof AboutEngineeringRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  ContactEngineeringEnquiryRoute: typeof ContactEngineeringEnquiryRoute
  ResourcesFaqsRoute: typeof ResourcesFaqsRoute
  SolutionsSolutionIdRoute: typeof SolutionsSolutionIdRoute
  TechnologyTechIdRoute: typeof TechnologyTechIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  TechnologyIndexRoute: typeof TechnologyIndexRoute
  ProductsCategoryIdRoute: typeof ProductsCategoryIdRoute
  ProductsCategoryIndexRoute: typeof ProductsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/engineering': {
      id: '/about/engineering'
      path: '/about/engineering'
      fullPath: '/about/engineering'
      preLoaderRoute: typeof AboutEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/engineering-enquiry': {
      id: '/contact/engineering-enquiry'
      path: '/contact/engineering-enquiry'
      fullPath: '/contact/engineering-enquiry'
      preLoaderRoute: typeof ContactEngineeringEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/faqs': {
      id: '/resources/faqs'
      path: '/resources/faqs'
      fullPath: '/resources/faqs'
      preLoaderRoute: typeof ResourcesFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$solutionId': {
      id: '/solutions/$solutionId'
      path: '/solutions/$solutionId'
      fullPath: '/solutions/$solutionId'
      preLoaderRoute: typeof SolutionsSolutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/': {
      id: '/technology/'
      path: '/technology'
      fullPath: '/technology/'
      preLoaderRoute: typeof TechnologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/$techId': {
      id: '/technology/$techId'
      path: '/technology/$techId'
      fullPath: '/technology/$techId'
      preLoaderRoute: typeof TechnologyTechIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/': {
      id: '/products/$category/'
      path: '/products/$category'
      fullPath: '/products/$category/'
      preLoaderRoute: typeof ProductsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/$id': {
      id: '/products/$category/$id'
      path: '/products/$category/$id'
      fullPath: '/products/$category/$id'
      preLoaderRoute: typeof ProductsCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  AboutEngineeringRoute: AboutEngineeringRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  ContactEngineeringEnquiryRoute: ContactEngineeringEnquiryRoute,
  ResourcesFaqsRoute: ResourcesFaqsRoute,
  SolutionsSolutionIdRoute: SolutionsSolutionIdRoute,
  TechnologyTechIdRoute: TechnologyTechIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  TechnologyIndexRoute: TechnologyIndexRoute,
  ProductsCategoryIdRoute: ProductsCategoryIdRoute,
  ProductsCategoryIndexRoute: ProductsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
