/**
 * Technology Stack Data Layer for INDUS Industrial Robotics
 * Covers 7 core engineering technology domains with comprehensive technical breakdowns.
 */

export interface TechnologyItem {
  id: string;
  title: string;
  shortDescription: string;
  heroSubtitle: string;
  whatIsIt: string;
  whyItMatters: string;
  howItWorks: string;
  mainComponents: {
    name: string;
    description: string;
  }[];
  industrialApplications: string[];
  integration: string;
  relatedProducts: {
    name: string;
    category: string;
    href: string;
  }[];
  technicalResources: {
    title: string;
    type: string;
    href: string;
  }[];
  faqs: {
    question: string;
    answer: string;
  }[];
}

export const technologiesData: TechnologyItem[] = [
  {
    id: "robotics",
    title: "Robotics",
    shortDescription:
      "Kinematic architectures, structural dynamics, and articulated mechanical manipulators.",
    heroSubtitle:
      "Engineered multi-axis kinematic systems designed for precision path following and continuous duty.",
    whatIsIt:
      "Robotics encompasses the mechanical design, kinematic linkage synthesis, and structural actuation of multi-axis industrial manipulators. An industrial robot coordinates serial or parallel kinematic chains where each actuated joint transforms input torque into spatial movement, positioning an end-effector within a calibrated Cartesian envelope.",
    whyItMatters:
      "High-speed precision manufacturing requires structural manipulators with high stiffness-to-weight ratios, minimal resonance, and repeatable path following under high accelerations. Selecting the proper kinematic format (SCARA, articulated 6-axis, collaborative, delta, Cartesian) dictates cycle speed, payload limits, and footprint efficiency.",
    howItWorks:
      "Commands generated by trajectory planners compute forward and inverse kinematics using Denavit-Hartenberg parameter matrices. Each joint module, powered by a precision servo and zero-backlash reducer, executes synchronized rotations that resolve into smooth spatial Cartesian trajectories at the tool center point (TCP).",
    mainComponents: [
      {
        name: "Base & Cast Structural Links",
        description:
          "High-rigidity cast ductile iron or aircraft-grade aluminum alloy castings designed via FEA to damp vibrations.",
      },
      {
        name: "Joint Reducers",
        description:
          "Zero-backlash strain wave (harmonic) and high-stiffness cycloidal reduction gearing stages.",
      },
      {
        name: "Brushless AC Servo Motors",
        description:
          "Permanent magnet synchronous motors delivering high power density in compact frames.",
      },
      {
        name: "Mechanical Brakes",
        description:
          "Fail-safe spring-applied electromagnetic brakes securing joints on e-stop or power interruption.",
      },
      {
        name: "Internal Harnessing",
        description:
          "High-flex cable looms routed internally through hollow joint bores to prevent wear and snagging.",
      },
    ],
    industrialApplications: [
      "Automotive Body Seam Welding",
      "Electronics Micro-Assembly",
      "Heavy Part Machine Tool Tending",
      "Pharmaceutical Cleanroom Packaging",
      "High-Volume Carton Palletizing",
    ],
    integration:
      "Pairs directly with industrial robot controllers, multi-axis servo drives, and deterministic fieldbuses (EtherCAT, PROFINET, Ethernet/IP) to coordinate with peripheral cell conveyors, tooling, and safety light curtains.",
    relatedProducts: [
      { name: "6-Axis Robotic Arm", category: "Robotic Arms", href: "/products/robotic-arms" },
      {
        name: "Industrial Handling Robot",
        category: "Industrial Robots",
        href: "/products/industrial-robots",
      },
      {
        name: "Precision Robotic Reducer",
        category: "Precision Reducers",
        href: "/products/precision-reducers",
      },
    ],
    technicalResources: [
      {
        title: "Kinematic Linkage Design & FEA Optimization",
        type: "Technical Article",
        href: "/resources?type=article",
      },
      {
        title: "ISO 9409-1 Flange Tooling Interface Standards",
        type: "Application Note",
        href: "/resources?type=app-note",
      },
    ],
    faqs: [
      {
        question: "What is the difference between repeatability and accuracy in robotics?",
        answer:
          "Repeatability measures the ability of a robot to return to the exact same taught physical point cycle after cycle (typically ±0.02mm to ±0.05mm). Accuracy measures how closely the robot's TCP reaches an absolute mathematically commanded point in space without prior teaching. Accuracy can be improved through kinematic calibration and laser tracker compensation.",
      },
      {
        question: "When should I choose a 6-axis robot over a 4-axis SCARA robot?",
        answer:
          "Choose a 4-axis SCARA for high-speed planar assembly, pick-and-place, or dispensing where parts remain horizontal (Z-axis plunge plus yaw). Choose a 6-axis articulated robot when the tool must approach workpieces from arbitrary compound 3D angles, such as complex welding, contoured deburring, or angled machine loading.",
      },
    ],
  },
  {
    id: "motion-control",
    title: "Motion Control",
    shortDescription:
      "Deterministic trajectory generation, path interpolation, and electronic gearing.",
    heroSubtitle:
      "Closing the loop between mathematical trajectory profiles and high-speed motor current regulation.",
    whatIsIt:
      "Motion control is the discipline of planning, coordinating, and regulating the physical position, velocity, and acceleration profiles of individual or synchronized machine axes. A motion controller acts as the central brain that computes kinematic paths and commands servo drives in real time.",
    whyItMatters:
      "Without deterministic motion control, multi-axis machines suffer from axis tracking skew, mechanical chatter, and rounding at high-speed corners. Advanced motion control provides smooth jerk-limited (S-curve) profiles, polynomial spline interpolation, and electronic camming that maximize speed while protecting mechanical drivetrains.",
    howItWorks:
      "The motion controller runs real-time trajectory algorithms at deterministic clock intervals (typically 250 microseconds to 1 millisecond). Trajectory setpoints are broadcast to servo amplifiers over synchronized industrial Ethernet (EtherCAT DC / PROFINET IRT). Drives close high-speed current, velocity, and position loops, comparing commanded points against encoder feedback.",
    mainComponents: [
      {
        name: "Trajectory Generator CPU",
        description:
          "Real-time multicore processor executing deterministic motion kernels (S-curve, splines, electronic cams).",
      },
      {
        name: "Fieldbus Master Interface",
        description:
          "EtherCAT master with distributed clock synchronization guaranteeing sub-microsecond bus jitter.",
      },
      {
        name: "Digital I/O & Touch Probe Triggers",
        description:
          "Fast hardware capture inputs registering sensor edges within nanoseconds for fly-by sorting.",
      },
      {
        name: "Kinematics Transformation Engine",
        description:
          "Converts Cartesian X-Y-Z coordinates into joint-specific motor angles dynamically.",
      },
    ],
    industrialApplications: [
      "Multi-Axis CNC Milling",
      "Synchronized Gantry Systems",
      "Rotary Die Cutting & Web Converting",
      "High-Speed Flying Shear Packaging",
      "Optical Metrology Scanning",
    ],
    integration:
      "Communicates upstream with plant SCADA and PLCs via OPC UA or Modbus TCP, and downstream with servo drives, stepper units, and remote I/O modules over EtherCAT or CANopen.",
    relatedProducts: [
      {
        name: "Coordinated Motion Controller",
        category: "Control Systems",
        href: "/products/control-systems",
      },
      { name: "Integrated Servo Actuator", category: "Actuators", href: "/products/actuators" },
      { name: "Linear Positioning Actuator", category: "Actuators", href: "/products/actuators" },
    ],
    technicalResources: [
      {
        title: "Real-Time Trajectory Generation Math",
        type: "Technical Article",
        href: "/resources?type=article",
      },
      {
        title: "Distributed Clock Synchronization Over EtherCAT",
        type: "Application Note",
        href: "/resources?type=app-note",
      },
    ],
    faqs: [
      {
        question: "What is distributed clock (DC) in EtherCAT motion control?",
        answer:
          "Distributed Clock is an EtherCAT mechanism that synchronizes the internal clocks of all network nodes to a single reference clock with sub-microsecond precision (typically <100ns). This ensures that every servo drive reads encoder feedback and applies torque output at the exact same physical instant, eliminating axis skew.",
      },
      {
        question: "What is the benefit of S-curve acceleration over trapezoidal acceleration?",
        answer:
          "Trapezoidal acceleration exhibits infinite jerk (the rate of change of acceleration) at ramp transitions, which excites mechanical resonance and causes structural vibration. S-curve acceleration introduces a continuous, finite jerk profile, resulting in smooth transitions that reduce machine wear and allow higher peak velocities.",
      },
    ],
  },
  {
    id: "servo",
    title: "Servo Technology",
    shortDescription:
      "Permanent magnet motors, digital drive amplifiers, and high-resolution feedback.",
    heroSubtitle:
      "High-dynamic closed-loop torque, velocity, and position control for modern robotics.",
    whatIsIt:
      "Servo technology refers to active, closed-loop electro-mechanical drive systems. A servo comprises a permanent magnet brushless AC/DC motor, an electronic power amplifier (drive), and a high-resolution position feedback sensor (encoder or resolver) that continuously corrects for load disturbances.",
    whyItMatters:
      "Unlike open-loop stepper motors that can lose steps under unexpected resistance, a servo system dynamically modulates electrical current to deliver precisely the torque required to maintain commanded trajectory, ensuring micro-radian precision and extreme dynamic responsiveness under varying loads.",
    howItWorks:
      "The servo amplifier uses Field-Oriented Control (FOC) to decouple motor stator currents into magnetic flux and torque-producing vectors. Current loops execute at 16 kHz to 32 kHz, velocity loops at 4 kHz to 8 kHz, and position loops at 1 kHz to 4 kHz. The drive continuously monitors rotor angle via absolute optical or magnetic encoders.",
    mainComponents: [
      {
        name: "Brushless Permanent Magnet Synchronous Motor (PMSM)",
        description:
          "Neodymium-iron-boron rotor magnets providing high torque-to-inertia ratio and thermal efficiency.",
      },
      {
        name: "Digital Servo Amplifier",
        description:
          "Silicon carbide (SiC) or IGBT power bridge executing pulse-width modulation (PWM) switching.",
      },
      {
        name: "Optical Absolute Encoder",
        description:
          "Multi-turn absolute encoder delivering up to 26-bit resolution (>67 million pulses per revolution) without battery backup.",
      },
      {
        name: "Dynamic Braking & Regeneration Resistor",
        description:
          "Dissipates kinetic energy during rapid axis deceleration or regenerates back to DC bus.",
      },
    ],
    industrialApplications: [
      "Robotic Joint Articulation",
      "Direct-Drive Rotary Tables",
      "High-Acceleration Pick & Place Axes",
      "Autonomous Mobile Vehicle Traction",
      "Tension Control in Reel Winders",
    ],
    integration:
      "Mounts directly onto precision reducers and linear actuators. Interfaces with controllers via digital fieldbuses (EtherCAT, CANopen) or high-speed analog/pulse-direction signals.",
    relatedProducts: [
      { name: "Integrated Servo Actuator", category: "Actuators", href: "/products/actuators" },
      {
        name: "Coordinated Motion Controller",
        category: "Control Systems",
        href: "/products/control-systems",
      },
      {
        name: "Precision Robotic Reducer",
        category: "Precision Reducers",
        href: "/products/precision-reducers",
      },
    ],
    technicalResources: [
      {
        title: "Field-Oriented Control (FOC) Implementation Deep-Dive",
        type: "Technical Article",
        href: "/resources?type=article",
      },
      {
        title: "Optical vs Magnetic Encoders in Harsh Industrial Environments",
        type: "Datasheet",
        href: "/resources?type=datasheet",
      },
    ],
    faqs: [
      {
        question: "What is the difference between an incremental and an absolute encoder?",
        answer:
          "An incremental encoder generates pulses as the motor turns and loses position reference upon power failure, requiring a physical homing routine to find zero. An absolute encoder assigns a unique digital code to every angular position, immediately knowing its exact multi-turn position upon power-up without requiring homing movements.",
      },
      {
        question: "Why is motor inertia matching critical in servo system sizing?",
        answer:
          "The ratio of load inertia to motor rotor inertia (inertia ratio) directly dictates control loop stability and tuning bandwidth. While modern drives with load observers can tolerate ratios up to 10:1 or 20:1, keeping the ratio closer to 1:1 or 5:1 yields faster settling times, zero overshoot, and maximum machine throughput.",
      },
    ],
  },
  {
    id: "automation",
    title: "Industrial Automation",
    shortDescription:
      "Deterministic fieldbuses, programmable logic controllers (PLCs), and cell safety logic.",
    heroSubtitle:
      "Connecting robotic mechanisms, cell sensors, safety interlocks, and plant control networks.",
    whatIsIt:
      "Industrial automation is the comprehensive system of hardware, control software, and industrial communication protocols that orchestrates manufacturing equipment without continuous human manual intervention. It coordinates cell sequencing, process interlocks, safety systems, and supervisory data acquisition (SCADA).",
    whyItMatters:
      "Modern factories cannot operate with isolated components. Industrial automation provides the standard fieldbuses (EtherCAT, PROFINET, EtherNet/IP), modular I/O, and certified safety architectures that allow robots, conveyors, pneumatic valves, and laser scanners to work in synchrony without collisions or bottlenecks.",
    howItWorks:
      "Industrial PLCs execute cyclic control routines conforming to IEC 61131-3 standards (Ladder Diagram, Structured Text, Function Block Diagram). Sensor inputs trigger logic branches that command actuators and drives over deterministic digital networks with cyclical scan times under 5 milliseconds.",
    mainComponents: [
      {
        name: "Programmable Logic Controllers (PLCs)",
        description:
          "Ruggedized industrial controllers executing logic sequencing, PID loops, and cell handshakes.",
      },
      {
        name: "Safety PLCs & Relay Modules",
        description:
          "Dual-channel redundant controllers certified up to SIL 3 / PLe (ISO 13849-1) for emergency stops and light curtains.",
      },
      {
        name: "Modular Distributed I/O",
        description:
          "IP67 field-mounted digital and analog I/O blocks reducing cabinet wiring complexity.",
      },
      {
        name: "Human-Machine Interface (HMI)",
        description:
          "Industrial touchscreen panels providing operators with diagnostic dashboards and recipe management.",
      },
    ],
    industrialApplications: [
      "Automated Assembly Lines",
      "Continuous Chemical Batch Processing",
      "Packaging & Carton Sorting Cells",
      "Robotic Welding Enclosures",
      "Semiconductor Cleanroom Material Handling",
    ],
    integration:
      "Serves as the supervisory layer connecting factory-floor devices (actuators, drives, sensors) to MES and enterprise ERP systems via OPC UA and industrial Ethernet.",
    relatedProducts: [
      {
        name: "Coordinated Motion Controller",
        category: "Control Systems",
        href: "/products/control-systems",
      },
      {
        name: "Industrial Handling Robot",
        category: "Industrial Robots",
        href: "/products/industrial-robots",
      },
      { name: "Integrated Servo Actuator", category: "Actuators", href: "/products/actuators" },
    ],
    technicalResources: [
      {
        title: "IEC 61131-3 Programming Standards & Motion Blocks",
        type: "Application Note",
        href: "/resources?type=app-note",
      },
      {
        title: "ISO 13849-1 Machine Safety Category Verification",
        type: "Technical Article",
        href: "/resources?type=article",
      },
    ],
    faqs: [
      {
        question: "What is the difference between a standard PLC and a Safety PLC?",
        answer:
          "A Safety PLC features internal redundant hardware architecture (such as dual microprocessors checking each other's execution) and self-testing diagnostic firmware certified to meet international safety standards (IEC 61508 SIL 3, ISO 13849-1 PLe). If any internal fault, wire break, or short circuit is detected, the safety PLC automatically forces the system into a safe de-energized state.",
      },
      {
        question: "How do fieldbuses compare: EtherCAT vs PROFINET vs EtherNet/IP?",
        answer:
          "EtherCAT uses 'processing on the fly' where frames pass through slave nodes with virtually zero delay, making it the premier choice for synchronized multi-axis servo motion control. PROFINET (especially IRT) and EtherNet/IP are widely deployed plant-level networks excellent for overall PLC-to-PLC communication, HMI interfaces, and general I/O.",
      },
    ],
  },
  {
    id: "sensors",
    title: "Sensors & Feedback",
    shortDescription:
      "Optical encoders, torque transducers, 3D laser profilers, and safety presence scanners.",
    heroSubtitle:
      "High-precision physical state feedback closing the loop on robotic positioning and cell safety.",
    whatIsIt:
      "Sensors and feedback devices measure physical parameters (position, velocity, force, torque, distance, temperature, presence) and convert them into high-speed digital or analog signals used by controllers to regulate movement and ensure operating safety.",
    whyItMatters:
      "Robotics cannot function open-loop. High-precision feedback determines how accurately a robot reaches a commanded point, how gently it inserts a delicate connector, and whether it safely decelerates when a human worker approaches the work zone.",
    howItWorks:
      "Optical encoders use calibrated reticles and photodetector arrays to measure shaft angle with sub-arcsecond resolution. Strain-gauge torque sensors measure micro-deflections in flexure beams to report joint loads. 3D laser triangulation cameras project laser lines onto targets to reconstruct 3D coordinate point clouds.",
    mainComponents: [
      {
        name: "Absolute Joint Rotary Encoders",
        description:
          "Single-turn and multi-turn optical/magnetic encoders reporting exact angular joint state.",
      },
      {
        name: "6-Axis Force-Torque Sensors",
        description:
          "Multi-axis strain transducers mounted between robot wrist and end-effector for force-controlled assembly.",
      },
      {
        name: "Safety Laser Scanners",
        description:
          "Time-of-flight LiDAR sensors defining programmable protective warning and stop safety zones.",
      },
      {
        name: "3D Machine Vision Cameras",
        description:
          "Structured light and laser profile sensors providing spatial coordinates for unstructured bin picking.",
      },
    ],
    industrialApplications: [
      "Collaborative Force-Limited Assembly",
      "Robotic Seam Tracking in Welding",
      "Safety Area Guarding Around Mobile Robots",
      "In-Line Dimensional Metrology",
      "Bin Picking of Unsorted Metal Castings",
    ],
    integration:
      "Connects directly to servo drive encoder feedback ports (BiSS-C, EnDat, SSI) or to controllers via EtherCAT, IO-Link, and Gigabit Ethernet.",
    relatedProducts: [
      { name: "Integrated Servo Actuator", category: "Actuators", href: "/products/actuators" },
      {
        name: "Coordinated Motion Controller",
        category: "Control Systems",
        href: "/products/control-systems",
      },
      {
        name: "AMR Drive Wheel Unit",
        category: "Robotic Wheels",
        href: "/products/robotic-wheels",
      },
    ],
    technicalResources: [
      {
        title: "BiSS-C vs EnDat 2.2 Protocol Comparison",
        type: "Technical Article",
        href: "/resources?type=article",
      },
      {
        title: "Force-Torque Sensor Calibration in Robotic Assembly",
        type: "Application Note",
        href: "/resources?type=app-note",
      },
    ],
    faqs: [
      {
        question:
          "What is the difference between primary motor encoder and secondary joint encoder?",
        answer:
          "A primary encoder is mounted directly to the motor shaft before the gearbox, providing fast velocity feedback for motor commutation. A secondary encoder is mounted on the output shaft of the gearbox after the reduction, directly measuring the true joint angle. Dual-encoder feedback eliminates errors caused by gearbox backlash and torsional compliance under heavy loads.",
      },
      {
        question: "What is IO-Link and why is it useful for industrial sensors?",
        answer:
          "IO-Link is a standardized point-to-point digital communication protocol for sensors and actuators. Unlike simple on/off digital sensors, IO-Link transmits process values, diagnostic parameters, and configuration data over standard unshielded 3-wire cables, allowing remote sensor parameterization and predictive maintenance.",
      },
    ],
  },
  {
    id: "ai-robotics",
    title: "AI & Intelligent Robotics",
    shortDescription:
      "Computer vision, adaptive trajectory planning, and neural obstacle avoidance for robotics.",
    heroSubtitle:
      "Transforming rigid automated machinery into perceptive, adaptable, and self-optimizing robotic systems.",
    whatIsIt:
      "AI & Intelligent Robotics integrates machine learning, neural perception, and dynamic path planning into industrial robots. It enables robots to see, interpret unstructured environments, handle non-uniform parts, and adjust trajectories in real time without rigid pre-programmed fixturing.",
    whyItMatters:
      "Traditional industrial robotics requires every part to be presented in an exact millimeter-precise fixture. In dynamic supply chains with thousands of SKUs or random bin presentations, intelligent robotics enables automated picking, sorting, and adaptive welding where traditional rigid programming fails.",
    howItWorks:
      "Neural networks trained on synthetic and real point clouds process 3D camera feeds in under 50 milliseconds, identifying part poses, grasp points, and collision boundaries. Path planning engines calculate collision-free inverse kinematic trajectories on the fly and stream setpoints to the motion controller.",
    mainComponents: [
      {
        name: "Edge AI Processing Unit",
        description:
          "Industrial GPU-accelerated edge computer executing neural inference models at the machine cell.",
      },
      {
        name: "RGB-D 3D Vision Sensors",
        description:
          "Stereo or time-of-flight cameras providing dense depth maps of random part bins.",
      },
      {
        name: "Grasp Planning Software",
        description:
          "Algorithmic solver evaluating suction and gripper grasp stability on organic or irregular shapes.",
      },
      {
        name: "Adaptive Path Solver",
        description:
          "Real-time obstacle avoidance algorithms dynamically routing arm motion around dynamic obstacles.",
      },
    ],
    industrialApplications: [
      "Random Bin Picking of Forged Blanks",
      "E-Commerce Mixed Parcel Induction",
      "Adaptive Seam Tracking on Varied Weldments",
      "Agricultural Automated Harvesting",
      "Autonomous Mobile Navigation in Dynamic Hubs",
    ],
    integration:
      "Bridges high-level Python/ROS/C++ vision stacks to deterministic industrial controllers over real-time Ethernet, maintaining strict safety supervisory boundaries.",
    relatedProducts: [
      { name: "6-Axis Robotic Arm", category: "Robotic Arms", href: "/products/robotic-arms" },
      {
        name: "Industrial Handling Robot",
        category: "Industrial Robots",
        href: "/products/industrial-robots",
      },
      {
        name: "AMR Drive Wheel Unit",
        category: "Robotic Wheels",
        href: "/products/robotic-wheels",
      },
    ],
    technicalResources: [
      {
        title: "Neural Grasp Planning in Unstructured Bin Picking",
        type: "Technical Article",
        href: "/resources?type=article",
      },
      {
        title: "Deterministic Safety Handshakes for AI Robot Cells",
        type: "Application Note",
        href: "/resources?type=app-note",
      },
    ],
    faqs: [
      {
        question: "How does AI handle latency and determinism when controlling industrial robots?",
        answer:
          "Industrial systems decouple AI inference from real-time motion control: the AI system plans high-level trajectories and target waypoints at asynchronous rates (e.g. 20 Hz), while the deterministic real-time motion controller executes trajectory interpolation and safety boundary clamping at 1 kHz to 4 kHz. If the AI system stalls or calculates an invalid path, the real-time controller immediately arrests motion safely.",
      },
      {
        question: "What is synthetic data generation for training robotic vision models?",
        answer:
          "Synthetic data generation involves rendering photorealistic 3D CAD models under millions of randomized lighting, texture, clutter, and occlusion variations in a physics simulator. This trains neural vision models to recognize real-world factory parts with high accuracy without requiring weeks of manual image labeling.",
      },
    ],
  },
  {
    id: "industry-4",
    title: "Industry 4.0",
    shortDescription:
      "Edge telemetry, digital twin simulation, and predictive maintenance architectures.",
    heroSubtitle:
      "Connecting shop-floor robotics to enterprise analytics for predictive maintenance and digital twins.",
    whatIsIt:
      "Industry 4.0 is the complete digital interconnectivity of manufacturing systems. It links physical robotic actuators, drives, and controllers through edge computing gateways to enterprise cloud platforms, enabling real-time OEE monitoring, predictive maintenance, and digital twin simulation.",
    whyItMatters:
      "Unplanned factory downtime costs manufacturers tens of thousands of dollars per minute. Industry 4.0 transforms maintenance from reactive fire-fighting to proactive scheduling: mechanical anomalies are detected weeks before joint failure, while digital twins validate line changes before physical steel is cut.",
    howItWorks:
      "Smart drives and controllers continuously sample torque ripple, vibration, and thermal metrics. An edge gateway computes spectral FFT analysis and packages health indexes into OPC UA or MQTT payloads sent securely to cloud dashboards or enterprise asset management (EAM) platforms.",
    mainComponents: [
      {
        name: "Edge Telemetry Gateways",
        description:
          "Ruggedized Linux-based industrial PCs hosting containerized analytics, OPC UA servers, and MQTT brokers.",
      },
      {
        name: "High-Frequency Vibration Monitors",
        description:
          "MEMS accelerometers mounted on gearbox bearings capturing acoustic signature anomalies.",
      },
      {
        name: "Digital Twin Kinematic Engine",
        description:
          "Physics-accurate digital simulation replicating real robot joint kinematics and cycle times.",
      },
      {
        name: "Cloud Analytics & OEE Platform",
        description:
          "Centralized telemetry dashboards tracking overall equipment effectiveness, cycle times, and energy consumption.",
      },
    ],
    industrialApplications: [
      "Plant-Wide Overall Equipment Effectiveness (OEE) Tracking",
      "Predictive Reducer & Bearing Maintenance",
      "Virtual Commissioning of Complex Production Lines",
      "Traceable Quality Serialization Per Unit",
      "Energy Consumption Profiling Across Peak Hours",
    ],
    integration:
      "Deploys on modern plant Ethernet infrastructures using open standards (OPC UA, MQTT, REST APIs), seamlessly coexisting with real-time fieldbuses without consuming motion bandwidth.",
    relatedProducts: [
      {
        name: "Coordinated Motion Controller",
        category: "Control Systems",
        href: "/products/control-systems",
      },
      { name: "Integrated Servo Actuator", category: "Actuators", href: "/products/actuators" },
      {
        name: "Industrial Handling Robot",
        category: "Industrial Robots",
        href: "/products/industrial-robots",
      },
    ],
    technicalResources: [
      {
        title: "Predictive Maintenance Algorithms on Strain Wave Gearing",
        type: "Technical Article",
        href: "/resources?type=article",
      },
      {
        title: "Digital Twin Virtual Commissioning Best Practices",
        type: "Application Note",
        href: "/resources?type=app-note",
      },
    ],
    faqs: [
      {
        question:
          "How does Industry 4.0 detect mechanical wear in a precision reducer before it breaks?",
        answer:
          "When gear teeth or bearing raceways begin to micro-pit, they generate distinct high-frequency vibration frequencies and minute motor current ripple harmonics during reversing cycles. By tracking the spectral FFT amplitude of these specific gear-meshing frequencies over time, the edge system detects degradation weeks before backlash expands or structural failure occurs.",
      },
      {
        question: "What is virtual commissioning and how does it save engineering cost?",
        answer:
          "Virtual commissioning connects the real PLC and motion controller hardware to a 3D digital twin of the machine cell before physical construction begins. Controls engineers test software logic, interlocks, collision boundaries, and cycle times in simulation, identifying 80% to 90% of software bugs and cutting physical on-site commissioning time in half.",
      },
    ],
  },
];

export const getTechnology = (id: string) => technologiesData.find((t) => t.id === id);
